/*
 * This source file was generated by the Gradle 'init' task
 */
import org.slf4j.Logger;

import config.ConfigLoader;
import config.LoggerConfig;
import services.FlowLogService;

public class App {
    private static final Logger logger = LoggerConfig.getLogger(App.class);

    public static void main(String[] args) {
        logger.info("Starting Flow Log Processor...");

        try {
            String flowLogFile = ConfigLoader.getProperty("flowlog.file");
            String lookupFile = ConfigLoader.getProperty("lookup.file");
            String outputFile = ConfigLoader.getProperty("output.file");

            FlowLogService service = new FlowLogService(flowLogFile, lookupFile, outputFile);
            service.process();

            logger.info("Flow Log Processing completed successfully.");
        } catch (Exception e) {
            logger.error("Error during processing: {}", e.getMessage(), e);
        }
    }
}
